export interface PlayerStats {
    recordLongestWinStreak: number;
    recordXpInAMatch: number;
    accuracy: number;
    losses: number;
    totalGamesPlayed: number;
    score: number;
    winLossRatio: number;
    gamesPlayed: number;
    deaths: number;
    wins: number;
    kdRatio: number;
    bestScore: number;
    recordDeathsInAMatch: number;
    bestSPM: number;
    recordKillsInAMatch: number;
    wlRatio: number;
    currentWinStreak: number;
    bestMatchXp: number;
    bestKD: number;
    kills: number;
    timePlayedTotal: number;
    headshots: number;
    recordKillStreak: number;
    bestPlants: number;
    misses: number;
    bestDamage: number;
    scorePerMinute: number;
    bestDeaths: number;
    bestKills: number;
    hits: number;
    bestKillStreak: number;
    // shotty
    AA12: number;
    C725: number;
    DP12: number;
    M26: number;
    Origin12: number;
    R870: number;
    // lmg
    M91: number;
    SA87: number;
    MG34: number;
    Holger: number;
    MK3: number;
    PKM: number;
    SX: number;
    // pistol
    CP: number;
    DE: number;
    G21: number;
    M1911: number;
    M9: number;
    P320: number;
    // launcher
    GR: number;
    JL: number;
    KG: number;
    MGL32: number;
    RPG7: number;
    // melee
    Knife: number;
    Kodachis: number;
    Kali: number;
    Riot: number;
    //smg
    AUG: number;
    Bizon: number;
    CX9: number;
    MP5: number;
    MP7: number;
    P90: number;
    Striker: number;
    Uzi: number;
    Fennec: number;
    // marksman
    Kar98k: number;
    SPR208: number;
    MK2Carbine: number;
    SKS: number;
    Crossbow: number;
    EBR14: number;
    // xniper
    AX50: number;
    Dragunov: number;
    HDR: number;
    Rytec: number;
    //assualt
    AK47: number;
    AN94: number;
    Oden: number;
    FAL: number;
    FR56: number;
    AMAX: number;
    Kilo: number;
    M13: number;
    M4A1: number;
    Scar: number;
    Grau: number;
    RAM7: number;
    ASVAL: number;
}