import { Injectable } from '@angular/core';
import { LifetimeStats } from '../models/lifetime-stats';
import { PlayerStatsLifetime } from '../models/player-stats';
import { PlayerStatsVanguard } from '../models/player-stats-vanguard';
import { VanguardLifetimeStats } from '../models/vanguard-stats';

@Injectable({
  providedIn: 'root',
})
export class StatsService {
  constructor() { }

  getEmptyWarzone(): any {
    return {
      wins: 0,
      kills: 0,
      kdRatio: 0,
      downs: 0,
      topTwentyFive: 0,
      topTen: 0,
      contracts: 0,
      revives: 0,
      topFive: 0,
      score: 0,
      timePlayed: 0,
      gamesPlayed: 0,
      tokens: 0,
      scorePerMinute: 0,
      cash: 0,
      deaths: 0,
    };
  }

  getEmptyWeekly(): any {
    return {
      kills: 0,
      medalXp: 0,
      objectivePlant: 0,
      objectiveMedalModeSdDefuseScore: 0,
      matchXp: 0,
      averageSpeedDuringMatch: 0,
      scoreXp: 0,
      accuracy: 0,
      losses: 0,
      wallBangs: 0,
      avgLifeTime: 0,
      shotsLanded: 0,
      objectiveMedalModeXDefendScore: 0,
      objectiveMedalModeXAssaultScore: 0,
      score: 0,
      totalXp: 0,
      headshots: 0,
      assists: 0,
      objectiveGainedGunRank: 0,
      draws: 0,
      rank: 0,
      scorePerMinute: 0,
      distanceTraveled: 0,
      deaths: 0,
      objectiveDestroyedEquipment: 0,
      wins: 0,
      kdRatio: 0,
      shotsMissed: 0,
      scorePerGame: 0,
      timePlayed: 0,
      headshotPercentage: 0,
      executions: 0,
      matchesPlayed: 0,
      suicides: 0,
      seasonRank: 0,
      wlRatio: 0,
      nearmisses: 0,
      objectivePerkMarkedTarget: 0,
      percentTimeMoving: 0,
      miscXp: 0,
      objectiveUavAssist: 0,
      objectiveLastManKill: 0,
      longestStreak: 0,
      objectiveDroppedGunRank: 0,
      damageDone: 0,
      shotsFired: 0,
      damageTaken: 0,
    };
  }

  convertLifetimeToVanguard(lifetime: VanguardLifetimeStats): PlayerStatsVanguard {
    let playerStats: PlayerStatsVanguard = {
      // root
      level: lifetime.level || 0,
      levelXpRemainder: lifetime.levelXpRemainder || 0,
      levelXpGained: lifetime.levelXpGained || 0,
      prestige: lifetime.prestige || 0,
      totalXp: lifetime.totalXp || 0,
      // accolade
      classChanges: lifetime.lifetime?.accoladeData?.properties?.classChanges || 0,
      highestAvgAltitude: lifetime.lifetime?.accoladeData?.properties?.highestAvgAltitude || 0,
      killsFromBehind: lifetime.lifetime?.accoladeData?.properties?.killsFromBehind || 0,
      lmgDeaths: lifetime.lifetime?.accoladeData?.properties?.lmgDeaths || 0,
      riotShieldDamageAbsorbed: lifetime.lifetime?.accoladeData?.properties?.riotShieldDamageAbsorbed || 0,
      flashbangHits: lifetime.lifetime?.accoladeData?.properties?.flashbangHits || 0,
      meleeKills: lifetime.lifetime?.accoladeData?.properties?.meleeKills || 0,
      tagsLargestBank: lifetime.lifetime?.accoladeData?.properties?.tagsLargestBank || 0,
      shotgunKills: lifetime.lifetime?.accoladeData?.properties?.shotgunKills || 0,
      highestScore: lifetime.lifetime?.accoladeData?.properties?.highestScore || 0,
      sniperDeaths: lifetime.lifetime?.accoladeData?.properties?.sniperDeaths || 0,
      timeProne: lifetime.lifetime?.accoladeData?.properties?.timeProne || 0,
      killstreakWhitePhosphorousKillsAssists: lifetime.lifetime?.accoladeData?.properties?.killstreakWhitePhosphorousKillsAssists || 0,
      shortestLife: lifetime.lifetime?.accoladeData?.properties?.shortestLife || 0,
      deathsFromBehind: lifetime.lifetime?.accoladeData?.properties?.deathsFromBehind || 0,
      higherRankedKills: lifetime.lifetime?.accoladeData?.properties?.higherRankedKills || 0,
      mostAssists: lifetime.lifetime?.accoladeData?.properties?.mostAssists || 0,
      leastKills: lifetime.lifetime?.accoladeData?.properties?.leastKills || 0,
      tagsDenied: lifetime.lifetime?.accoladeData?.properties?.tagsDenied || 0,
      killstreakWheelsonKills: lifetime.lifetime?.accoladeData?.properties?.killstreakWheelsonKills || 0,
      sniperHeadshots: lifetime.lifetime?.accoladeData?.properties?.sniperHeadshots || 0,
      killstreakJuggernautKills: lifetime.lifetime?.accoladeData?.properties?.killstreakJuggernautKills || 0,
      smokesUsed: lifetime.lifetime?.accoladeData?.properties?.smokesUsed || 0,
      avengerKills: lifetime.lifetime?.accoladeData?.properties?.avengerKills || 0,
      decoyHits: lifetime.lifetime?.accoladeData?.properties?.decoyHits || 0,
      killstreakCarePackageUsed: lifetime.lifetime?.accoladeData?.properties?.killstreakCarePackageUsed || 0,
      mostCaptures: lifetime.lifetime?.accoladeData?.properties?.mostCaptures || 0,
      molotovKills: lifetime.lifetime?.accoladeData?.properties?.molotovKills || 0,
      mostMultiKills: lifetime.lifetime?.accoladeData?.properties?.mostMultiKills || 0,
      gasHits: lifetime.lifetime?.accoladeData?.properties?.gasHits || 0,
      comebackKills: lifetime.lifetime?.accoladeData?.properties?.comebackKills || 0,
      lmgHeadshots: lifetime.lifetime?.accoladeData?.properties?.lmgHeadshots || 0,
      smgDeaths: lifetime.lifetime?.accoladeData?.properties?.smgDeaths || 0,
      explosiveKills: lifetime.lifetime?.accoladeData?.properties?.explosiveKills || 0,
      carrierKills: lifetime.lifetime?.accoladeData?.properties?.carrierKills || 0,
      deployableCoverUsed: lifetime.lifetime?.accoladeData?.properties?.deployableCoverUsed || 0,
      thermiteKills: lifetime.lifetime?.accoladeData?.properties?.thermiteKills || 0,
      arKills: lifetime.lifetime?.accoladeData?.properties?.arKills || 0,
      clutch: lifetime.lifetime?.accoladeData?.properties?.clutch || 0,
      mostDefends: lifetime.lifetime?.accoladeData?.properties?.mostDefends || 0,
      mostExplosiveEliminations: lifetime.lifetime?.accoladeData?.properties?.mostExplosiveEliminations || 0,
      survivorKills: lifetime.lifetime?.accoladeData?.properties?.survivorKills || 0,
      killstreakGunshipKills: lifetime.lifetime?.accoladeData?.properties?.killstreakGunshipKills || 0,
      timeSpentAsPassenger: lifetime.lifetime?.accoladeData?.properties?.timeSpentAsPassenger || 0,
      returns: lifetime.lifetime?.accoladeData?.properties?.returns || 0,
      smgHeadshots: lifetime.lifetime?.accoladeData?.properties?.smgHeadshots || 0,
      launcherDeaths: lifetime.lifetime?.accoladeData?.properties?.launcherDeaths || 0,
      oneShotOneKills: lifetime.lifetime?.accoladeData?.properties?.oneShotOneKills || 0,
      ammoBoxUsed: lifetime.lifetime?.accoladeData?.properties?.ammoBoxUsed || 0,
      spawnSelectSquad: lifetime.lifetime?.accoladeData?.properties?.spawnSelectSquad || 0,
      weaponPickups: lifetime.lifetime?.accoladeData?.properties?.weaponPickups || 0,
      pointBlankKills: lifetime.lifetime?.accoladeData?.properties?.pointBlankKills || 0,
      tagsCaptured: lifetime.lifetime?.accoladeData?.properties?.tagsCaptured || 0,
      secondHighestScore: lifetime.lifetime?.accoladeData?.properties?.secondHighestScore || 0,
      killstreakGroundKills: lifetime.lifetime?.accoladeData?.properties?.killstreakGroundKills || 0,
      highestEDRatio: lifetime.lifetime?.accoladeData?.properties?.highestEDRatio || 0,
      distanceTraveledInVehicle: lifetime.lifetime?.accoladeData?.properties?.distanceTraveledInVehicle || 0,
      longestLife: lifetime.lifetime?.accoladeData?.properties?.longestLife || 0,
      stunHits: lifetime.lifetime?.accoladeData?.properties?.stunHits || 0,
      spawnSelectFlag: lifetime.lifetime?.accoladeData?.properties?.spawnSelectFlag || 0,
      shotgunHeadshots: lifetime.lifetime?.accoladeData?.properties?.shotgunHeadshots || 0,
      bombDefused: lifetime.lifetime?.accoladeData?.properties?.bombDefused || 0,
      snapshotHits: lifetime.lifetime?.accoladeData?.properties?.snapshotHits || 0,
      noKillsWithDeath: lifetime.lifetime?.accoladeData?.properties?.noKillsWithDeath || 0,
      killstreakAUAVAssists: lifetime.lifetime?.accoladeData?.properties?.killstreakAUAVAssists || 0,
      killstreakPersonalUAVKills: lifetime.lifetime?.accoladeData?.properties?.killstreakPersonalUAVKills || 0,
      tacticalInsertionSpawns: lifetime.lifetime?.accoladeData?.properties?.tacticalInsertionSpawns || 0,
      mostKillstreaksDestroyed: lifetime.lifetime?.accoladeData?.properties?.mostKillstreaksDestroyed || 0,
      launcherKills: lifetime.lifetime?.accoladeData?.properties?.launcherKills || 0,
      spawnSelectVehicle: lifetime.lifetime?.accoladeData?.properties?.spawnSelectVehicle || 0,
      mostKillsLeastDeaths: lifetime.lifetime?.accoladeData?.properties?.mostKillsLeastDeaths || 0,
      mostHeadshotKills: lifetime.lifetime?.accoladeData?.properties?.mostHeadshotKills || 0,
      defends: lifetime.lifetime?.accoladeData?.properties?.defends || 0,
      timeSpentAsDriver: lifetime.lifetime?.accoladeData?.properties?.timeSpentAsDriver || 0,
      bombDetonated: lifetime.lifetime?.accoladeData?.properties?.bombDetonated || 0,
      thirdHighestScore: lifetime.lifetime?.accoladeData?.properties?.thirdHighestScore || 0,
      arHeadshots: lifetime.lifetime?.accoladeData?.properties?.arHeadshots || 0,
      mostFinishingMoves: lifetime.lifetime?.accoladeData?.properties?.mostFinishingMoves || 0,
      timeOnPoint: lifetime.lifetime?.accoladeData?.properties?.timeOnPoint || 0,
      lmgKills: lifetime.lifetime?.accoladeData?.properties?.lmgKills || 0,
      killstreakUAVAssists: lifetime.lifetime?.accoladeData?.properties?.killstreakUAVAssists || 0,
      carepackagesCaptured: lifetime.lifetime?.accoladeData?.properties?.carepackagesCaptured || 0,
      mostKillsLongestStreak: lifetime.lifetime?.accoladeData?.properties?.mostKillsLongestStreak || 0,
      killstreakCruiseMissileKills: lifetime.lifetime?.accoladeData?.properties?.killstreakCruiseMissileKills || 0,
      longestStreak: lifetime.lifetime?.accoladeData?.properties?.longestStreak || 0,
      destroyedKillstreaks: lifetime.lifetime?.accoladeData?.properties?.destroyedKillstreaks || 0,
      hipfireKills: lifetime.lifetime?.accoladeData?.properties?.hipfireKills || 0,
      stimDamageHealed: lifetime.lifetime?.accoladeData?.properties?.stimDamageHealed || 0,
      killstreaksUsed: lifetime.lifetime?.accoladeData?.properties?.killstreaksUsed || 0,
      skippedKillcams: lifetime.lifetime?.accoladeData?.properties?.skippedKillcams || 0,
      leastAssists: lifetime.lifetime?.accoladeData?.properties?.leastAssists || 0,
      mostMultikills: lifetime.lifetime?.accoladeData?.properties?.mostMultikills || 0,
      highestRankedKills: lifetime.lifetime?.accoladeData?.properties?.highestRankedKills || 0,
      killstreakAirstrikeKills: lifetime.lifetime?.accoladeData?.properties?.killstreakAirstrikeKills || 0,
      distanceTravelled: lifetime.lifetime?.accoladeData?.properties?.distanceTravelled || 0,
      munitionsBoxUsed: lifetime.lifetime?.accoladeData?.properties?.munitionsBoxUsed || 0,
      killstreakKills: lifetime.lifetime?.accoladeData?.properties?.killstreakKills || 0,
      semtexKills: lifetime.lifetime?.accoladeData?.properties?.semtexKills || 0,
      penetrationKills: lifetime.lifetime?.accoladeData?.properties?.penetrationKills || 0,
      explosionsSurvived: lifetime.lifetime?.accoladeData?.properties?.explosionsSurvived || 0,
      highestMultikill: lifetime.lifetime?.accoladeData?.properties?.highestMultikill || 0,
      arDeaths: lifetime.lifetime?.accoladeData?.properties?.arDeaths || 0,
      mostTimeNearAllies: lifetime.lifetime?.accoladeData?.properties?.mostTimeNearAllies || 0,
      longshotKills: lifetime.lifetime?.accoladeData?.properties?.longshotKills || 0,
      proximityMineKills: lifetime.lifetime?.accoladeData?.properties?.proximityMineKills || 0,
      tagsMegaBanked: lifetime.lifetime?.accoladeData?.properties?.tagsMegaBanked || 0,
      mostKillsMostHeadshots: lifetime.lifetime?.accoladeData?.properties?.mostKillsMostHeadshots || 0,
      firstInfected: lifetime.lifetime?.accoladeData?.properties?.firstInfected || 0,
      killstreakCUAVAssists: lifetime.lifetime?.accoladeData?.properties?.killstreakCUAVAssists || 0,
      throwingKnifeKills: lifetime.lifetime?.accoladeData?.properties?.throwingKnifeKills || 0,
      executionKills: lifetime.lifetime?.accoladeData?.properties?.executionKills || 0,
      lastSurvivor: lifetime.lifetime?.accoladeData?.properties?.lastSurvivor || 0,
      reconDroneMarks: lifetime.lifetime?.accoladeData?.properties?.reconDroneMarks || 0,
      deadSilenceKills: lifetime.lifetime?.accoladeData?.properties?.deadSilenceKills || 0,
      mostTimeNearEnemies: lifetime.lifetime?.accoladeData?.properties?.mostTimeNearEnemies || 0,
      revengeKills: lifetime.lifetime?.accoladeData?.properties?.revengeKills || 0,
      infectedKills: lifetime.lifetime?.accoladeData?.properties?.infectedKills || 0,
      killEnemyTeam: lifetime.lifetime?.accoladeData?.properties?.killEnemyTeam || 0,
      sniperKills: lifetime.lifetime?.accoladeData?.properties?.sniperKills || 0,
      killstreakCluserStrikeKills: lifetime.lifetime?.accoladeData?.properties?.killstreakCluserStrikeKills || 0,
      meleeDeaths: lifetime.lifetime?.accoladeData?.properties?.meleeDeaths || 0,
      timeWatchingKillcams: lifetime.lifetime?.accoladeData?.properties?.timeWatchingKillcams || 0,
      killstreakTankKills: lifetime.lifetime?.accoladeData?.properties?.killstreakTankKills || 0,
      noKillNoDeath: lifetime.lifetime?.accoladeData?.properties?.noKillNoDeath || 0,
      shotgunDeaths: lifetime.lifetime?.accoladeData?.properties?.shotgunDeaths || 0,
      killstreakChopperGunnerKills: lifetime.lifetime?.accoladeData?.properties?.killstreakChopperGunnerKills || 0,
      shotsFired: lifetime.lifetime?.accoladeData?.properties?.shotsFired || 0,
      stoppingPowerKills: lifetime.lifetime?.accoladeData?.properties?.stoppingPowerKills || 0,
      pistolPeaths: lifetime.lifetime?.accoladeData?.properties?.pistolPeaths || 0,
      killstreakShieldTurretKills: lifetime.lifetime?.accoladeData?.properties?.killstreakShieldTurretKills || 0,
      timeCrouched: lifetime.lifetime?.accoladeData?.properties?.timeCrouched || 0,
      noDeathsFromBehind: lifetime.lifetime?.accoladeData?.properties?.noDeathsFromBehind || 0,
      bombPlanted: lifetime.lifetime?.accoladeData?.properties?.bombPlanted || 0,
      setbacks: lifetime.lifetime?.accoladeData?.properties?.setbacks || 0,
      smgKills: lifetime.lifetime?.accoladeData?.properties?.smgKills || 0,
      claymoreKills: lifetime.lifetime?.accoladeData?.properties?.claymoreKills || 0,
      kills10NoDeaths: lifetime.lifetime?.accoladeData?.properties?.kills10NoDeaths || 0,
      pistolHeadshots: lifetime.lifetime?.accoladeData?.properties?.pistolHeadshots || 0,
      killstreakVTOLJetKills: lifetime.lifetime?.accoladeData?.properties?.killstreakVTOLJetKills || 0,
      mostDeaths: lifetime.lifetime?.accoladeData?.properties?.mostDeaths || 0,
      adsKills: lifetime.lifetime?.accoladeData?.properties?.adsKills || 0,
      empDroneHits: lifetime.lifetime?.accoladeData?.properties?.empDroneHits || 0,
      defenderKills: lifetime.lifetime?.accoladeData?.properties?.defenderKills || 0,
      c4LethalKills: lifetime.lifetime?.accoladeData?.properties?.c4LethalKills || 0,
      launcherHeadshots: lifetime.lifetime?.accoladeData?.properties?.launcherHeadshots || 0,
      timesSelectedAsSquadLeader: lifetime.lifetime?.accoladeData?.properties?.timesSelectedAsSquadLeader || 0,
      killstreakAirKills: lifetime.lifetime?.accoladeData?.properties?.killstreakAirKills || 0,
      assaults: lifetime.lifetime?.accoladeData?.properties?.assaults || 0,
      fragKills: lifetime.lifetime?.accoladeData?.properties?.fragKills || 0,
      killstreakEmergencyAirdropUsed: lifetime.lifetime?.accoladeData?.properties?.killstreakEmergencyAirdropUsed || 0,
      captures: lifetime.lifetime?.accoladeData?.properties?.captures || 0,
      killstreakChopperSupportKills: lifetime.lifetime?.accoladeData?.properties?.killstreakChopperSupportKills || 0,
      spawnSelectBase: lifetime.lifetime?.accoladeData?.properties?.spawnSelectBase || 0,
      noKill10Deaths: lifetime.lifetime?.accoladeData?.properties?.noKill10Deaths || 0,
      mostMeleeKills: lifetime.lifetime?.accoladeData?.properties?.mostMeleeKills || 0,
      leastDeaths: lifetime.lifetime?.accoladeData?.properties?.leastDeaths || 0,
      killstreakSentryGunKills: lifetime.lifetime?.accoladeData?.properties?.killstreakSentryGunKills || 0,
      longestTimeSpentOnWeapon: lifetime.lifetime?.accoladeData?.properties?.longestTimeSpentOnWeapon || 0,
      lowerRankedKills: lifetime.lifetime?.accoladeData?.properties?.lowerRankedKills || 0,
      mostEliminations: lifetime.lifetime?.accoladeData?.properties?.mostEliminations || 0,
      trophySystemHits: lifetime.lifetime?.accoladeData?.properties?.trophySystemHits || 0,
      clutchRevives: lifetime.lifetime?.accoladeData?.properties?.clutchRevives || 0,
      lowestAvgAltitude: lifetime.lifetime?.accoladeData?.properties?.lowestAvgAltitude || 0,
      pickups: lifetime.lifetime?.accoladeData?.properties?.pickups || 0,
      pistolKills: lifetime.lifetime?.accoladeData?.properties?.pistolKills || 0,
      mostKillstreaksCalledIn: lifetime.lifetime?.accoladeData?.properties?.mostKillstreaksCalledIn || 0,
      reloads: lifetime.lifetime?.accoladeData?.properties?.reloads || 0,
      // all
      recordLongestWinStreak: lifetime.lifetime?.all.properties?.recordLongestWinStreak || 0,
      recordXpInAMatch: lifetime.lifetime?.all.properties?.recordXpInAMatch || 0,
      accuracy: lifetime.lifetime?.all.properties?.accuracy || 0,
      losses: lifetime.lifetime?.all.properties?.losses || 0,
      totalGamesPlayed: lifetime.lifetime?.all.properties?.totalGamesPlayed || 0,
      score: lifetime.lifetime?.all.properties?.score || 0,
      winLossRatio: lifetime.lifetime?.all.properties?.winLossRatio || 0,
      totalShots: lifetime.lifetime?.all.properties?.totalShots || 0,
      bestScoreXp: lifetime.lifetime?.all.properties?.bestScoreXp || 0,
      gamesPlayed: lifetime.lifetime?.all.properties?.gamesPlayed || 0,
      bestSquardKills: lifetime.lifetime?.all.properties?.bestSquardKills || 0,
      bestSguardWave: lifetime.lifetime?.all.properties?.bestSguardWave || 0,
      bestConfirmed: lifetime.lifetime?.all.properties?.bestConfirmed || 0,
      deaths: lifetime.lifetime?.all.properties?.deaths || 0,
      wins: lifetime.lifetime?.all.properties?.wins || 0,
      bestSquardCrates: lifetime.lifetime?.all.properties?.bestSquardCrates || 0,
      kdRatio: lifetime.lifetime?.all.properties?.kdRatio || 0,
      bestAssists: lifetime.lifetime?.all.properties?.bestAssists || 0,
      bestFieldgoals: lifetime.lifetime?.all.properties?.bestFieldgoals || 0,
      bestScore: lifetime.lifetime?.all.properties?.bestScore || 0,
      recordDeathsInAMatch: lifetime.lifetime?.all.properties?.recordDeathsInAMatch || 0,
      scorePerGame: lifetime.lifetime?.all.properties?.scorePerGame || 0,
      bestSPM: lifetime.lifetime?.all.properties?.bestSPM || 0,
      bestKillChains: lifetime.lifetime?.all.properties?.bestKillChains || 0,
      recordKillsInAMatch: lifetime.lifetime?.all.properties?.recordKillsInAMatch || 0,
      suicides: lifetime.lifetime?.all.properties?.suicides || 0,
      wlRatio: lifetime.lifetime?.all.properties?.wlRatio || 0,
      currentWinStreak: lifetime.lifetime?.all.properties?.currentWinStreak || 0,
      bestMatchBonusXp: lifetime.lifetime?.all.properties?.bestMatchBonusXp || 0,
      bestMatchXp: lifetime.lifetime?.all.properties?.bestMatchXp || 0,
      bestSguardWeaponLevel: lifetime.lifetime?.all.properties?.bestSguardWeaponLevel || 0,
      bestContracts: lifetime.lifetime?.all.properties?.bestContracts || 0,
      bestKD: lifetime.lifetime?.all.properties?.bestKD || 0,
      kills: lifetime.lifetime?.all.properties?.kills || 0,
      bestKillsAsInfected: lifetime.lifetime?.all.properties?.bestKillsAsInfected || 0,
      bestReturns: lifetime.lifetime?.all.properties?.bestReturns || 0,
      bestStabs: lifetime.lifetime?.all.properties?.bestStabs || 0,
      bestKillsAsSurvivor: lifetime.lifetime?.all.properties?.bestKillsAsSurvivor || 0,
      timePlayedTotal: lifetime.lifetime?.all.properties?.timePlayedTotal || 0,
      bestDestructions: lifetime.lifetime?.all.properties?.bestDestructions || 0,
      headshots: lifetime.lifetime?.all.properties?.headshots || 0,
      bestRescues: lifetime.lifetime?.all.properties?.bestRescues || 0,
      assists: lifetime.lifetime?.all.properties?.assists || 0,
      ties: lifetime.lifetime?.all.properties?.ties || 0,
      recordKillStreak: lifetime.lifetime?.all.properties?.recordKillStreak || 0,
      bestPlants: lifetime.lifetime?.all.properties?.bestPlants || 0,
      misses: lifetime.lifetime?.all.properties?.misses || 0,
      bestDowns: lifetime.lifetime?.all.properties?.bestDowns || 0,
      bestDamage: lifetime.lifetime?.all.properties?.bestDamage || 0,
      bestSetbacks: lifetime.lifetime?.all.properties?.bestSetbacks || 0,
      bestTouchdowns: lifetime.lifetime?.all.properties?.bestTouchdowns || 0,
      scorePerMinute: lifetime.lifetime?.all.properties?.scorePerMinute || 0,
      bestDeaths: lifetime.lifetime?.all.properties?.bestDeaths || 0,
      bestMedalXp: lifetime.lifetime?.all.properties?.bestMedalXp || 0,
      bestDefends: lifetime.lifetime?.all.properties?.bestDefends || 0,
      bestSquardRevives: lifetime.lifetime?.all.properties?.bestSquardRevives || 0,
      bestKills: lifetime.lifetime?.all.properties?.bestKills || 0,
      bestDefuses: lifetime.lifetime?.all.properties?.bestDefuses || 0,
      bestCaptures: lifetime.lifetime?.all.properties?.bestCaptures || 0,
      hits: lifetime.lifetime?.all.properties?.hits || 0,
      bestKillStreak: lifetime.lifetime?.all.properties?.bestKillStreak || 0,
      bestDenied: lifetime.lifetime?.all.properties?.bestDenied || 0,
      // melee
      melee_knife: lifetime.lifetime?.itemData?.weapon_melee.s4_me_knife.properties?.kills || 0,
      melee_fists: lifetime.lifetime?.itemData?.weapon_melee.s4_me_fists.properties?.kills || 0,
      melee_katana: lifetime.lifetime?.itemData?.weapon_melee.s4_me_katana.properties?.kills || 0,
      melee_rindigo: lifetime.lifetime?.itemData?.weapon_melee.s4_me_rindigo.properties?.kills || 0,
      // pistol
      pi_ttango33: lifetime.lifetime?.itemData?.weapon_pistol.s4_pi_ttango33.properties?.kills || 0,
      pi_wecho: lifetime.lifetime?.itemData?.weapon_pistol.s4_pi_wecho.properties?.kills || 0,
      pi_malpha96: lifetime.lifetime?.itemData?.weapon_pistol.s4_pi_malpha96.properties?.kills || 0,
      pi_luniform08: lifetime.lifetime?.itemData?.weapon_pistol.s4_pi_luniform08.properties?.kills || 0,
      pi_mike1911: lifetime.lifetime?.itemData?.weapon_pistol.s4_pi_mike1911.properties?.kills || 0,
      // shotty
      sh_lindia98: lifetime.lifetime?.itemData?.weapon_shotgun.s4_sh_lindia98.properties?.kills || 0,
      sh_mike97: lifetime.lifetime?.itemData?.weapon_shotgun.s4_sh_mike97.properties?.kills || 0,
      sh_bromeo5: lifetime.lifetime?.itemData?.weapon_shotgun.s4_sh_bromeo5.properties?.kills || 0,
      sh_becho: lifetime.lifetime?.itemData?.weapon_shotgun.s4_sh_becho.properties?.kills || 0,
      // smg
      smg_mgolf42: lifetime.lifetime?.itemData?.weapon_smg.s4_mg_mgolf42.properties?.kills || 0,
      smg_streak: lifetime.lifetime?.itemData?.weapon_smg.s4_mg_streak.properties?.kills || 0,
      smg_dpapa27: lifetime.lifetime?.itemData?.weapon_smg.s4_mg_dpapa27.properties?.kills || 0,
      smg_bromeo37: lifetime.lifetime?.itemData?.weapon_smg.s4_mg_bromeo37.properties?.kills || 0,
      smg_tyankee11: lifetime.lifetime?.itemData?.weapon_smg.s4_mg_tyankee11.properties?.kills || 0,
      smg_juniform: lifetime.lifetime?.itemData?.weapon_smg.s4_mg_juniform.properties?.kills || 0,
      // assault
      ar_chotel15: lifetime.lifetime?.itemData?.weapon_assault_rifle.s4_ar_chotel15.properties?.kills || 0,
      ar_bromeopg: lifetime.lifetime?.itemData?.weapon_assault_rifle.s4_ar_bromeopg.properties?.kills || 0,
      ar_fecho: lifetime.lifetime?.itemData?.weapon_assault_rifle.s4_ar_fecho.properties?.kills || 0,
      ar_balpha: lifetime.lifetime?.itemData?.weapon_assault_rifle.s4_ar_balpha.properties?.kills || 0,
      ar_hyankee44: lifetime.lifetime?.itemData?.weapon_assault_rifle.s4_ar_hyankee44.properties?.kills || 0,
      ar_chotel41: lifetime.lifetime?.itemData?.weapon_assault_rifle.s4_ar_chotel41.properties?.kills || 0,
      ar_asierra44: lifetime.lifetime?.itemData?.weapon_assault_rifle.s4_ar_asierra44.properties?.kills || 0,
      ar_stango44: lifetime.lifetime?.itemData?.weapon_assault_rifle.s4_ar_stango44.properties?.kills || 0,
      ar_voscar: lifetime.lifetime?.itemData?.weapon_assault_rifle.s4_ar_voscar.properties?.kills || 0,
      // lmg
      lmg_palpha: lifetime.lifetime?.itemData?.weapon_lmg.s4_la_palpha.properties?.kills || 0,
      lmg_m1bravo: lifetime.lifetime?.itemData?.weapon_lmg.s4_la_m1bravo.properties?.kills || 0,
      lmg_walpha2: lifetime.lifetime?.itemData?.weapon_lmg.s4_la_walpha2.properties?.kills || 0,
      lmg_mkilo1: lifetime.lifetime?.itemData?.weapon_lmg.s4_la_mkilo1.properties?.kills || 0,
      lmg_palpha42: lifetime.lifetime?.itemData?.weapon_lmg.s4_la_palpha42.properties?.kills || 0,
      // sniper
      mr_moscar: lifetime.lifetime?.itemData?.weapon_sniper.s4_mr_moscar.properties?.kills || 0,
      mr_ptango41: lifetime.lifetime?.itemData?.weapon_sniper.s4_mr_ptango41.properties?.kills || 0,
      mr_gecho43: lifetime.lifetime?.itemData?.weapon_sniper.s4_mr_gecho43.properties?.kills || 0,
      mr_aromeo99: lifetime.lifetime?.itemData?.weapon_sniper.s4_mr_aromeo99.properties?.kills || 0,
      mr_lecho: lifetime.lifetime?.itemData?.weapon_sniper.s4_mr_lecho.properties?.kills || 0,
      mr_kalpha98: lifetime.lifetime?.itemData?.weapon_sniper.s4_mr_kalpha98.properties?.kills || 0,
      mr_svictor40: lifetime.lifetime?.itemData?.weapon_sniper.s4_mr_svictor40.properties?.kills || 0,
      mr_m1golf: lifetime.lifetime?.itemData?.weapon_sniper.s4_mr_m1golf.properties?.kills || 0,
    };
    return playerStats;
  }

  convertLifetimeStatsToPlayerStatsLifetime(lifetime: LifetimeStats): PlayerStatsLifetime {
    let playerstats: PlayerStatsLifetime = {
      recordLongestWinStreak: lifetime.lifetime?.all.properties?.recordLongestWinStreak || 0,
      recordXpInAMatch: lifetime.lifetime?.all.properties?.recordXpInAMatch || 0,
      accuracy: lifetime.lifetime?.all.properties?.accuracy || 0,
      losses: lifetime.lifetime?.all.properties?.losses || 0,
      totalGamesPlayed: lifetime.lifetime?.all.properties?.totalGamesPlayed || 0,
      score: lifetime.lifetime?.all.properties?.score || 0,
      winLossRatio: lifetime.lifetime?.all.properties?.winLossRatio || 0,
      gamesPlayed: lifetime.lifetime?.all.properties?.gamesPlayed || 0,
      deaths: lifetime.lifetime?.all.properties?.deaths || 0,
      wins: lifetime.lifetime?.all.properties?.wins || 0,
      kdRatio: lifetime.lifetime?.all.properties?.kdRatio || 0,
      bestScore: lifetime.lifetime?.all.properties?.bestScore || 0,
      recordDeathsInAMatch: lifetime.lifetime?.all.properties?.recordDeathsInAMatch || 0,
      bestSPM: lifetime.lifetime?.all.properties?.bestSPM || 0,
      recordKillsInAMatch: lifetime.lifetime?.all.properties?.recordKillsInAMatch || 0,
      wlRatio: lifetime.lifetime?.all.properties?.wlRatio || 0,
      currentWinStreak: lifetime.lifetime?.all.properties?.currentWinStreak || 0,
      bestMatchXp: lifetime.lifetime?.all.properties?.bestMatchXp || 0,
      bestKD: lifetime.lifetime?.all.properties?.bestKD || 0,
      kills: lifetime.lifetime?.all.properties?.kills || 0,
      timePlayedTotal: lifetime.lifetime?.all.properties?.timePlayedTotal || 0,
      headshots: lifetime.lifetime?.all.properties?.headshots || 0,
      recordKillStreak: lifetime.lifetime?.all.properties?.recordKillStreak || 0,
      bestPlants: lifetime.lifetime?.all.properties?.bestPlants || 0,
      misses: lifetime.lifetime?.all.properties?.misses || 0,
      bestDamage: lifetime.lifetime?.all.properties?.bestDamage || 0,
      scorePerMinute: lifetime.lifetime?.all.properties?.scorePerMinute || 0,
      bestDeaths: lifetime.lifetime?.all.properties?.bestDeaths || 0,
      bestKills: lifetime.lifetime?.all.properties?.bestKills || 0,
      hits: lifetime.lifetime?.all.properties?.hits || 0,
      bestKillStreak: lifetime.lifetime?.all.properties?.bestKillStreak || 0,
      // shotty
      AA12: lifetime.lifetime?.itemData?.weapon_shotgun.iw8_sh_aalpha12.properties?.kills || 0,
      C725: lifetime.lifetime?.itemData?.weapon_shotgun.iw8_sh_charlie725.properties?.kills || 0,
      DP12: lifetime.lifetime?.itemData?.weapon_shotgun.iw8_sh_dpapa12.properties?.kills || 0,
      M26: lifetime.lifetime?.itemData?.weapon_shotgun.iw8_sh_mike26.properties?.kills || 0,
      Origin12: lifetime.lifetime?.itemData?.weapon_shotgun.iw8_sh_oscar12.properties?.kills || 0,
      R870: lifetime.lifetime?.itemData?.weapon_shotgun.iw8_sh_romeo870.properties?.kills || 0,
      // // lmg
      M91: lifetime.lifetime?.itemData?.weapon_lmg.iw8_lm_kilo121.properties?.kills || 0,
      SA87: lifetime.lifetime?.itemData?.weapon_lmg.iw8_lm_lima86.properties?.kills || 0,
      MG34: lifetime.lifetime?.itemData?.weapon_lmg.iw8_lm_mgolf34.properties?.kills || 0,
      Holger: lifetime.lifetime?.itemData?.weapon_lmg.iw8_lm_mgolf36.properties?.kills || 0,
      MK3: lifetime.lifetime?.itemData?.weapon_lmg.iw8_lm_mkilo3.properties?.kills || 0,
      PKM: lifetime.lifetime?.itemData?.weapon_lmg.iw8_lm_pkilo.properties?.kills || 0,
      SX: lifetime.lifetime?.itemData?.weapon_lmg.iw8_lm_sierrax.properties?.kills || 0,
      // // pistol
      CP: lifetime.lifetime?.itemData?.weapon_pistol.iw8_pi_cpapa.properties?.kills || 0,
      DE: lifetime.lifetime?.itemData?.weapon_pistol.iw8_pi_decho.properties?.kills || 0,
      G21: lifetime.lifetime?.itemData?.weapon_pistol.iw8_pi_golf21.properties?.kills || 0,
      M1911: lifetime.lifetime?.itemData?.weapon_pistol.iw8_pi_mike1911.properties?.kills || 0,
      M9: lifetime.lifetime?.itemData?.weapon_pistol.iw8_pi_mike9.properties?.kills || 0,
      P320: lifetime.lifetime?.itemData?.weapon_pistol.iw8_pi_papa320.properties?.kills || 0,
      // // launcher
      GR: lifetime.lifetime?.itemData?.weapon_launcher.iw8_la_gromeo.properties?.kills || 0,
      JL: lifetime.lifetime?.itemData?.weapon_launcher.iw8_la_juliet.properties?.kills || 0,
      KG: lifetime.lifetime?.itemData?.weapon_launcher.iw8_la_kgolf.properties?.kills || 0,
      MGL32: lifetime.lifetime?.itemData?.weapon_launcher.iw8_la_mike32.properties?.kills || 0,
      RPG7: lifetime.lifetime?.itemData?.weapon_launcher.iw8_la_rpapa7.properties?.kills || 0,
      // melee
      Knife: lifetime.lifetime?.itemData?.weapon_melee.iw8_knife.properties?.kills || 0,
      Kodachis: lifetime.lifetime?.itemData?.weapon_melee.iw8_me_akimboblades.properties?.kills || 0,
      Kali: lifetime.lifetime?.itemData?.weapon_melee.iw8_me_akimboblunt.properties?.kills || 0,
      Riot: lifetime.lifetime?.itemData?.weapon_other.iw8_me_riotshield.properties?.kills || 0,
      // //smg
      AUG: lifetime.lifetime?.itemData?.weapon_smg.iw8_sm_augolf.properties?.kills || 0,
      Bizon: lifetime.lifetime?.itemData?.weapon_smg.iw8_sm_beta.properties?.kills || 0,
      CX9: lifetime.lifetime?.itemData?.weapon_smg.iw8_sm_charlie9.properties?.kills || 0,
      MP5: lifetime.lifetime?.itemData?.weapon_smg.iw8_sm_mpapa5.properties?.kills || 0,
      MP7: lifetime.lifetime?.itemData?.weapon_smg.iw8_sm_mpapa7.properties?.kills || 0,
      P90: lifetime.lifetime?.itemData?.weapon_smg.iw8_sm_papa90.properties?.kills || 0,
      Striker: lifetime.lifetime?.itemData?.weapon_smg.iw8_sm_smgolf45.properties?.kills || 0,
      Uzi: lifetime.lifetime?.itemData?.weapon_smg.iw8_sm_uzulu.properties?.kills || 0,
      Fennec: lifetime.lifetime?.itemData?.weapon_smg.iw8_sm_victor.properties?.kills || 0,
      // // marksman
      Kar98k: lifetime.lifetime?.itemData?.weapon_marksman.iw8_sn_kilo98.properties?.kills || 0,
      SPR208: lifetime.lifetime?.itemData?.weapon_marksman.iw8_sn_romeo700.properties?.kills || 0,
      MK2Carbine: lifetime.lifetime?.itemData?.weapon_marksman.iw8_sn_sbeta.properties?.kills || 0,
      SKS: lifetime.lifetime?.itemData?.weapon_marksman.iw8_sn_sksierra.properties?.kills || 0,
      Crossbow: lifetime.lifetime?.itemData?.weapon_marksman.iw8_sn_crossbow.properties?.kills || 0,
      EBR14: lifetime.lifetime?.itemData?.weapon_marksman.iw8_sn_mike14.properties?.kills || 0,
      // // xniper
      AX50: lifetime.lifetime?.itemData?.weapon_sniper.iw8_sn_alpha50.properties?.kills || 0,
      Dragunov: lifetime.lifetime?.itemData?.weapon_sniper.iw8_sn_delta.properties?.kills || 0,
      HDR: lifetime.lifetime?.itemData?.weapon_sniper.iw8_sn_hdromeo.properties?.kills || 0,
      Rytec: lifetime.lifetime?.itemData?.weapon_sniper.iw8_sn_xmike109.properties?.kills || 0,
      // //assualt
      AK47: lifetime.lifetime?.itemData?.weapon_assault_rifle.iw8_ar_akilo47.properties?.kills || 0,
      AN94: lifetime.lifetime?.itemData?.weapon_assault_rifle.iw8_ar_anovember94.properties?.kills || 0,
      Oden: lifetime.lifetime?.itemData?.weapon_assault_rifle.iw8_ar_asierra12.properties?.kills || 0,
      FAL: lifetime.lifetime?.itemData?.weapon_assault_rifle.iw8_ar_falima.properties?.kills || 0,
      FR56: lifetime.lifetime?.itemData?.weapon_assault_rifle.iw8_ar_falpha.properties?.kills || 0,
      AMAX: lifetime.lifetime?.itemData?.weapon_assault_rifle.iw8_ar_galima.properties?.kills || 0,
      Kilo: lifetime.lifetime?.itemData?.weapon_assault_rifle.iw8_ar_kilo433.properties?.kills || 0,
      M13: lifetime.lifetime?.itemData?.weapon_assault_rifle.iw8_ar_mcharlie.properties?.kills || 0,
      M4A1: lifetime.lifetime?.itemData?.weapon_assault_rifle.iw8_ar_mike4.properties?.kills || 0,
      Scar: lifetime.lifetime?.itemData?.weapon_assault_rifle.iw8_ar_scharlie.properties?.kills || 0,
      Grau: lifetime.lifetime?.itemData?.weapon_assault_rifle.iw8_ar_sierra552.properties?.kills || 0,
      RAM7: lifetime.lifetime?.itemData?.weapon_assault_rifle.iw8_ar_tango21.properties?.kills || 0,
      ASVAL: lifetime.lifetime?.itemData?.weapon_assault_rifle.iw8_ar_valpha.properties?.kills || 0,
      // // SD
      SDKills: lifetime.lifetime?.mode.sd.properties?.kills || 0,
      SDKD: lifetime.lifetime?.mode.sd.properties?.kdRatio || 0,
      SDDeath: lifetime.lifetime?.mode.sd.properties?.deaths || 0,
      SDHours: lifetime.lifetime?.mode.sd.properties?.timePlayed || 0,
      SDPlant: lifetime.lifetime?.mode.sd.properties?.plants || 0,
      SDDefuse: lifetime.lifetime?.mode.sd.properties?.defuses || 0,
      SDScore: lifetime.lifetime?.mode.sd.properties?.score || 0,
      SDScoreMin: lifetime.lifetime?.mode.sd.properties?.scorePerMinute || 0,
      // // Accolade
      killsFromBehind: lifetime.lifetime?.accoladeData?.properties?.killsFromBehind || 0,
      lmgDeaths: lifetime.lifetime?.accoladeData?.properties?.lmgDeaths || 0,
      riotShieldDamageAbsorbed: lifetime.lifetime?.accoladeData?.properties?.riotShieldDamageAbsorbed || 0,
      flashbangHits: lifetime.lifetime?.accoladeData?.properties?.flashbangHits || 0,
      meleeKills: lifetime.lifetime?.accoladeData?.properties?.meleeKills || 0,
      shotgunKills: lifetime.lifetime?.accoladeData?.properties?.shotgunKills || 0,
      sniperDeaths: lifetime.lifetime?.accoladeData?.properties?.sniperDeaths || 0,
      timeProne: lifetime.lifetime?.accoladeData?.properties?.timeProne || 0,
      shortestLife: lifetime.lifetime?.accoladeData?.properties?.shortestLife || 0,
      sniperHeadshots: lifetime.lifetime?.accoladeData?.properties?.sniperHeadshots || 0,
      smokesUsed: lifetime.lifetime?.accoladeData?.properties?.smokesUsed || 0,
      molotovKills: lifetime.lifetime?.accoladeData?.properties?.molotovKills || 0,
      gasHits: lifetime.lifetime?.accoladeData?.properties?.gasHits || 0,
      lmgHeadshots: lifetime.lifetime?.accoladeData?.properties?.lmgHeadshots || 0,
      smgDeaths: lifetime.lifetime?.accoladeData?.properties?.smgDeaths || 0,
      thermiteKills: lifetime.lifetime?.accoladeData?.properties?.thermiteKills || 0,
      arKills: lifetime.lifetime?.accoladeData?.properties?.arKills || 0,
      c4Kills: lifetime.lifetime?.accoladeData?.properties?.c4Kills || 0,
      suicides: lifetime.lifetime?.accoladeData?.properties?.suicides || 0,
      clutch: lifetime.lifetime?.accoladeData?.properties?.clutch || 0,
      survivorKills: lifetime.lifetime?.accoladeData?.properties?.survivorKills || 0,
      smgHeadshots: lifetime.lifetime?.accoladeData?.properties?.smgHeadshots || 0,
      launcherDeaths: lifetime.lifetime?.accoladeData?.properties?.launcherDeaths || 0,
      oneShotOneKills: lifetime.lifetime?.accoladeData?.properties?.oneShotOneKills || 0,
      ammoBoxUsed: lifetime.lifetime?.accoladeData?.properties?.ammoBoxUsed || 0,
      distanceTraveledInVehicle: lifetime.lifetime?.accoladeData?.properties?.distanceTraveledInVehicle || 0,
      longestLife: lifetime.lifetime?.accoladeData?.properties?.longestLife || 0,
      stunHits: lifetime.lifetime?.accoladeData?.properties?.stunHits || 0,
      shotgunHeadshots: lifetime.lifetime?.accoladeData?.properties?.shotgunHeadshots || 0,
      bombDefused: lifetime.lifetime?.accoladeData?.properties?.bombDefused || 0,
      launcherKills: lifetime.lifetime?.accoladeData?.properties?.launcherKills || 0,
      mostKills: lifetime.lifetime?.accoladeData?.properties?.mostKills || 0,
      defends: lifetime.lifetime?.accoladeData?.properties?.defends || 0,
      bombDetonated: lifetime.lifetime?.accoladeData?.properties?.bombDetonated || 0,
      arHeadshots: lifetime.lifetime?.accoladeData?.properties?.arHeadshots || 0,
      timeOnPoint: lifetime.lifetime?.accoladeData?.properties?.timeOnPoint || 0,
      lmgKills: lifetime.lifetime?.accoladeData?.properties?.lmgKills || 0,
      mostKillsLongestStreak: lifetime.lifetime?.accoladeData?.properties?.mostKillsLongestStreak || 0,
      longestStreak: lifetime.lifetime?.accoladeData?.properties?.longestStreak || 0,
      hipfireKills: lifetime.lifetime?.accoladeData?.properties?.hipfireKills || 0,
      stimDamageHealed: lifetime.lifetime?.accoladeData?.properties?.stimDamageHealed || 0,
      mostMultikills: lifetime.lifetime?.accoladeData?.properties?.mostMultikills || 0,
      distanceTravelled: lifetime.lifetime?.accoladeData?.properties?.distanceTravelled || 0,
      killstreakKills: lifetime.lifetime?.accoladeData?.properties?.killstreakKills || 0,
      semtexKills: lifetime.lifetime?.accoladeData?.properties?.semtexKills || 0,
      penetrationKills: lifetime.lifetime?.accoladeData?.properties?.penetrationKills || 0,
      highestMultikill: lifetime.lifetime?.accoladeData?.properties?.highestMultikill || 0,
      arDeaths: lifetime.lifetime?.accoladeData?.properties?.arDeaths || 0,
      longshotKills: lifetime.lifetime?.accoladeData?.properties?.longshotKills || 0,
      throwingKnifeKills: lifetime.lifetime?.accoladeData?.properties?.throwingKnifeKills || 0,
      executionKills: lifetime.lifetime?.accoladeData?.properties?.executionKills || 0,
      deadSilenceKills: lifetime.lifetime?.accoladeData?.properties?.deadSilenceKills || 0,
      revengeKills: lifetime.lifetime?.accoladeData?.properties?.revengeKills || 0,
      infectedKills: lifetime.lifetime?.accoladeData?.properties?.infectedKills || 0,
      killEnemyTeam: lifetime.lifetime?.accoladeData?.properties?.killEnemyTeam || 0,
      sniperKills: lifetime.lifetime?.accoladeData?.properties?.sniperKills || 0,
      meleeDeaths: lifetime.lifetime?.accoladeData?.properties?.meleeDeaths || 0,
      noKillNoDeath: lifetime.lifetime?.accoladeData?.properties?.noKillNoDeath || 0,
      shotgunDeaths: lifetime.lifetime?.accoladeData?.properties?.shotgunDeaths || 0,
      shotsFired: lifetime.lifetime?.accoladeData?.properties?.shotsFired || 0,
      stoppingPowerKills: lifetime.lifetime?.accoladeData?.properties?.stoppingPowerKills || 0,
      pistolPeaths: lifetime.lifetime?.accoladeData?.properties?.pistolPeaths || 0,
      timeCrouched: lifetime.lifetime?.accoladeData?.properties?.timeCrouched || 0,
      bombPlanted: lifetime.lifetime?.accoladeData?.properties?.bombPlanted || 0,
      smgKills: lifetime.lifetime?.accoladeData?.properties?.smgKills || 0,
      claymoreKills: lifetime.lifetime?.accoladeData?.properties?.claymoreKills || 0,
      pistolHeadshots: lifetime.lifetime?.accoladeData?.properties?.pistolHeadshots || 0,
      mostDeaths: lifetime.lifetime?.accoladeData?.properties?.mostDeaths || 0,
      adsKills: lifetime.lifetime?.accoladeData?.properties?.adsKills || 0,
      defenderKills: lifetime.lifetime?.accoladeData?.properties?.defenderKills || 0,
      launcherHeadshots: lifetime.lifetime?.accoladeData?.properties?.launcherHeadshots || 0,
      assaults: lifetime.lifetime?.accoladeData?.properties?.assaults || 0,
      fragKills: lifetime.lifetime?.accoladeData?.properties?.fragKills || 0,
      captures: lifetime.lifetime?.accoladeData?.properties?.captures || 0,
      noKill10Deaths: lifetime.lifetime?.accoladeData?.properties?.noKill10Deaths || 0,
      leastDeaths: lifetime.lifetime?.accoladeData?.properties?.leastDeaths || 0,
      longestTimeSpentOnWeapon: lifetime.lifetime?.accoladeData?.properties?.longestTimeSpentOnWeapon || 0,
      pistolKills: lifetime.lifetime?.accoladeData?.properties?.pistolKills || 0,
    };
    return playerstats;
  }
}
